backend:
  name: git-gateway
  branch: master
media_folder: public/img/uploads
public_folder: /img/uploads
collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
