backend:
  name: git-gateway
  branch: master
media_folder: public/img/uploads
public_folder: /img/uploads
collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Page1"
        name: "page1"
        file: "content/page1.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Page2"
          name: "page2"
          file: "content/page2.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
      - label: "Page3"
          name: "page3"
          file: "content/page3.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
      - label: "Page4"
          name: "page4"
          file: "content/page4.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
