backend:
  name: git-gateway
  branch: master
media_folder: public/img/uploads
public_folder: /img/uploads
collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About", name: "about", widget: "markdown" }
      - label: "Projects"
        name: "projects"
        file: "content/projects.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Project"
            name: "project"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Datetime", name: "datetime", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "Page3"
        name: "page3"
        file: "content/page3.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Page4"
        name: "page4"
        file: "content/page4.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
